[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://slide-extractor-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://slide-extractor-api.onrender.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://slide-extractor-api.onrender.com"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://slide-extractor-api.onrender.com"
