services:
  # Backend API service
  - type: web
    name: slide-extractor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: CORS_ALLOWED_ORIGINS
        value: "https://latenighter.netlify.app,https://slide-extractor-frontend.onrender.com,https://slide-extractor.netlify.app,http://localhost:3000,http://localhost:5173"
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in the Render dashboard
      - key: MAX_CONTENT_LENGTH
        value: "104857600"  # 100MB for large video uploads
      - key: UPLOAD_TIMEOUT
        value: "600"  # 10 minutes for video processing
