services:
  # Backend API service
  - type: web
    name: slide-extractor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5000
      - key: ENVIRONMENT
        value: production
      - key: CORS_ALLOWED_ORIGINS
        value: "*"  # Allow all origins by default, can be changed in Render dashboard
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in the Render dashboard
