services:
  # Backend API service
  - type: web
    name: slide-extractor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5000
      - key: ENVIRONMENT
        value: production
      - key: CORS_ALLOWED_ORIGINS
        value: "https://LazyToppers.netlify.app,http://localhost:5173,http://localhost:5174,http://localhost:5175,https://slide-extractor-frontend.onrender.com"  # Allow multiple origins
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in the Render dashboard
